version: 40
jobs:
- name: Publish Site
  steps:
  - !CheckoutStep
    name: Get Code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !PublishSiteStep
    name: Publish Site
    artifacts: '*'
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
